version: '2'
mpp-vars:
  name: base
  ssh_permit_password_auth: true
  use_containers_extra_store: true


pipelines:
- name: rootfs
  build: name:build
  stages:

  # Install some special RPMs
  - type: org.osbuild.rpm
    options:
      gpgkeys:
      - mpp-eval: distro_gpg_keys
      disable_dracut: true
      exclude:
        docs: true
    inputs:
      packages:
        type: org.osbuild.files
        origin: org.osbuild.source
        mpp-depsolve:
          architecture: $arch
          ignore-weak-deps: true
          module-platform-id: $distro_module_id
          baseurl: $distro_baseurl_repo
          repos:
            mpp-join:
            - mpp-eval: image_repos
            - mpp-eval: extra_repos
          packages:
            mpp-join:
            - mpp-eval: image_rpms
            - - hostname
              - less
              - openssh-clients
              - openssh-server
              - podman
              - rsync
              - tar
              - tree
              - vim
              - wget
          excludes:
          - dracut-config-rescue

  # Get the CS10 base container in
  - type: org.osbuild.skopeo
    inputs:
      images:
        type: org.osbuild.containers
        origin: org.osbuild.source
        mpp-resolve-images:
          images:
            - source: quay.io/centos/centos
              tag: stream10-development
              name: localhost/cs10
    options:
      destination:
        type: containers-storage
        storage-path:
          mpp-eval: containers_extra_store

  # Get the CS10 base container in
  - type: org.osbuild.skopeo
    inputs:
      images:
        type: org.osbuild.containers
        origin: org.osbuild.source
        mpp-resolve-images:
          images:
            - source: localhost/validator
              tag: latest
              name: localhost/validator
              containers-transport: containers-storage 
    options:
      destination:
        type: containers-storage
        storage-path:
          mpp-eval: containers_extra_store

  # Create group for the guest user
  - type: org.osbuild.groups
    options:
      groups:
        guest:
          gid:
            mpp-eval: guest_gid

  # Create the guest user
  - type: org.osbuild.users
    options:
      users:
        guest:
          password:
            mpp-eval: guest_password
          gid:
            mpp-eval: guest_gid
          uid:
            mpp-eval: guest_uid

  # Enable ssh on the image and allow root login
  - type: org.osbuild.sshd.config
    options:
      config:
        PasswordAuthentication:
          mpp-eval: ssh_permit_password_auth
        PermitRootLogin:
          mpp-eval: ssh_permit_root_login

  - type: org.osbuild.systemd
    options:
      enabled_services:
      - sshd.service

